### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by h-ucchi** [h-ucchi/protospace-37078#1]
自身のProtoSpaceのURL（本番環境](https://protospace-37078.herokuapp.com/)

**Comment by soll02solglas** [comment]
@h-ucchi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] ログイン・ログアウトの状態に関わらず、一覧表示されている画像をクリックすると、該当する詳細ページへ遷移するようにしましょう。
→現状ログアウト状態で画像をクリックするとログインページが表示されてしまいます。

- [x] コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう。
→現状コメントフォームをからのまま送信するとエラー画面が表示されてしまいます。
<img width="662" alt="スクリーンショット 2022-02-06 10 37 39" src="https://user-images.githubusercontent.com/30042165/152664758-2da6410d-5e65-40a5-935f-7ad57fa050ed.png">

- [x] ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう。
→現状ログアウト状態で一覧ページのユーザー名をクリックするとログインページに遷移してしまいます。ログイン状態で一覧ページのユーザー名をクリックするとプロトタイプの詳細ページに遷移してしまいます。

- [x] ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされるようにしましょう
→現状ログアウト状態で新規投稿ページのURLを直接入力して遷移しようとすると、トップページへ遷移してしまいます。

- [x] ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう
→現状、他のユーザーのプロトタイプ編集ページに遷移して編集できてしまいます。

※プロトタイプの詳細機能に関してはログアウト状態での動作確認ができない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@h-ucchi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について一部を除き修正が確認できました。ありがとうございます。
新たに修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [x] **プロトタイプ詳細ページにて、ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・ キャッチコピー・コンセプト）が表示されるよう修正しましょう**
・プロトタイプのタイトルが、入力したタイトルでなく「プロトタイプのタイトル」という文言が表示されてしまいます。
・ログイン状態の投稿者以外は「投稿者名」が表示されていない状態です。
<img width="596" alt="スクリーンショット_2022-02-06_17_24_09" src="https://user-images.githubusercontent.com/54050089/152673014-94dfa786-7d1e-4a47-bad8-ff229626ad39.png">
<img width="615" alt="スクリーンショット_2022-02-06_17_27_58" src="https://user-images.githubusercontent.com/54050089/152673179-edcf0340-c56a-4c31-84e0-0b32afd791da.png">

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
詳細ページの投稿者名をクリックすると、別のプロトタイプ詳細ページに遷移してしまいます。

https://user-images.githubusercontent.com/54050089/152673335-19e8de4f-f1ce-49bd-ae4e-a1d2ea342b2d.mov

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされるよう修正しましょう**
・ログアウト状態のユーザーがプロトタイプ新規投稿ページに遷移できてしまいます。
・ログアウト状態のユーザーがプロトタイプ編集ページに遷移しようとすると、エラー画面に遷移してしまいます。




修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by h-ucchi** [comment]
修正したので、ご確認お願いします。

https://protospace-37078.herokuapp.com/

**Comment by snkw-works** [comment]
@h-ucchi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について一部を除き修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、「ログインページ」にリダイレクトされるよう修正しましょう**
プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、「トップページ」に遷移してしまいます。（正しい挙動は「ログインページ」へ遷移です。）

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるよう修正しましょう**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！

**Comment by h-ucchi** [comment]
ご確認ありがとうございます！
Issueクローズさせていただきます。
